### ISSUE TITLE
Combine all js file into one file.

### ISSUE THREAD

**Issue by vishal-px** [weihanchen/angular-screenshot#10]
Hi @weihanchen,

    Is it possible to combine all js file into one file?

For eg-: https://prnt.sc/i0nxtq
 So, if I will include only combined.js then all are are include into html page automatic.

Thanks.

**Comment by weihanchen** [comment]
Maybe  you should use [gulp](https://gulpjs.com/) or [webpack](https://webpack.js.org/) with your project to bundle js files.

**Comment by vishal-px** [comment]
Thanks, brother gulp works for me.
