### ISSUE TITLE
Dynamic SVG created by D3 is taking time to capture screen using angular-screenshot

### ISSUE THREAD

**Issue by bhaumikbarad** [weihanchen/angular-screenshot#13]
When there are more number of SVG (7 SVG elements) created by D3 charts then to capture screen using angular-screenshot takes more than 100s.

What can be the solution to improve performance. Please help.

Is this known issue of this library ?

Thanks,
Bhaumik

**Comment by weihanchen** [comment]
This lib depend on [dom-to-image](https://github.com/tsayen/dom-to-image) and there are known performance bottlenecks [issue](https://github.com/tsayen/dom-to-image/issues/245).


But there are some suggestions on this topic that take part of the area when screen captures, avoiding dealing with too many dom structures at once.
