### ISSUE TITLE
Support for Internet Explorer and Firefox

### ISSUE THREAD

**Issue by leebanpaul** [weihanchen/angular-screenshot#2]
Hi Weihanchen,
    Thanks for the tool, it is really very useful, Could you please let me know know if this tool works on IE 11 or firefox?
 I noticed that in my app it only worked for Chrome and not in IE and Firefox. Just wanted to make sure, if  it is an issue with my code or it is not actually supported on IE or firefox

**Comment by weihanchen** [comment]
Unfortunately, IE and Firefox is not supported by this lib.
