### ISSUE TITLE
how to send screenshot email via email

### ISSUE THREAD

**Issue by jeffreydinh** [weihanchen/angular-screenshot#3]

**Comment by jeffreydinh** [comment]
is there an option to screenshot, but not download, and send it via email by using nodemailer?

**Comment by weihanchen** [comment]
I will try to design `toPng()` api then return image `dataUrl`, and you can send `dataUrl` to your backend api,  then use nodemailer to implement your feature.
Send image to backend api use nodejs express like below, but not implement with nodemailer:
```javascript
const express = require('express');
const fs = require('fs');
const bodyParser = require('body-parser');
const app = express();
app.use(bodyParser.json({limit: '50mb'}));
app.post('/upload', (req, res) => {
   try {
      const imageData = req.body.imageData;
      const base64Data = imageData.replace(/^data:image\/\w+;base64,/, "");
      const dataBuffer = new Buffer(base64Data, 'base64');
      fs.writeFileSync('out.png', dataBuffer);
      res.send('success!');
   } catch (error) {
      res.send(error);
   }
});

app.listen(8000);
```

POST imageData to api
```sh
curl -X POST -H "Content-Type: application/json"  -d '{"imageData": "${dataUrl}"}' http://localhost:8000/upload

```

You can reference lastest release [docs](https://github.com/weihanchen/angular-screenshot/blob/master/README.md) with `toPng` api.
