### ISSUE TITLE
Have support angular2  version? thank's

### ISSUE THREAD

**Issue by thomas0728** [weihanchen/angular-screenshot#4]

**Comment by weihanchen** [comment]
Sorry, Angular2+ has not been supported so far, but there are some explanations for the upgraded version:
1. The part of the Angular directive only handles the dom element specification, style and other related configuration, and passes the screenshot canvas operation to [util/dom-process.js](https://github.com/weihanchen/angular-screenshot/blob/master/src/utils/dom-process.js).

2. Design the core dom operation part to [util/dom-process.js](https://github.com/weihanchen/angular-screenshot/blob/master/src/utils/dom-process.js), and thereby obtain the screenshot block selected by user.

3. Convert the specified element to svg via [dom-to-image](https://github.com/tsayen/dom-to-image) and then crop it according to the user's screenshot block, and finally convert to png .

So if you want to move this project to Angular2+, the difference is just the logic of the directive.

However, the author himself did not have a deeper research on Angular2+ and did not have time to upgrade. I hope that someone who is willing to contact me will help upgrade to Angular2+.

Thanks,
Weihanchen

**Comment by weihanchen** [comment]
I am working on the [ng2-screenshot](https://github.com/weihanchen/ng2-screenshot), but it has not been released yet.

Please give me some time to finish.

Thanks.
