### ISSUE TITLE
How can I use the angular-screenshot by angular 2.x.x or angular4.x.x?

### ISSUE THREAD

**Issue by HsuNick** [weihanchen/angular-screenshot#5]
I hope use in the angular 2.x.x or angular4.x.x, but I don't know what to doing.

**Comment by Manaskumar119** [comment]
@weihanchen  , suggest something on this

**Comment by weihanchen** [comment]
Sorry, Angular2+ has not been supported so far, but there are some explanations for the upgraded version:
1. The part of the Angular directive only handles the dom element specification, style and other related configuration, and passes the screenshot canvas operation to [util/dom-process.js](https://github.com/weihanchen/angular-screenshot/blob/master/src/utils/dom-process.js).

2. Design the core dom operation part to [util/dom-process.js](https://github.com/weihanchen/angular-screenshot/blob/master/src/utils/dom-process.js), and thereby obtain the screenshot block selected by user.

3. Convert the specified element to svg via [dom-to-image](https://github.com/tsayen/dom-to-image) and then crop it according to the user's screenshot block, and finally convert to png .

So if you want to move this project to Angular2+, the difference is just the logic of the directive.

However, the author himself did not have a deeper research on Angular2+ and did not have time to upgrade. I hope that someone who is willing to contact me will help upgrade to Angular2+.

Thanks,
Weihanchen

**Comment by bsingh06** [comment]
@weihanchen I am willing to upgrade it to Angular4.

**Comment by yogen-darji-hs** [comment]
@bsingh06 @weihanchen  did you get chance to update it? Or any other library in Angular 4+?

**Comment by CarlosTirado** [comment]
Is there another option today?

**Comment by weihanchen** [comment]
I am working on the [ng2-screenshot](https://github.com/weihanchen/ng2-screenshot), but it has not been released yet.

Please give me some time to finish.

Thanks.

**Comment by weihanchen** [comment]
[ng2-screenshot](https://github.com/weihanchen/ng2-screenshot) already release v0.1.2


#4

**Comment by charlenebuena** [comment]
AMAZING! THANKS
